Dim fso, folder, folder2, file, file2, cdFolder, bgImg, compDir, fileExt, mainDir, cdToday, runPS, imgMgc, imgPos
Dim dateMonth, dateDay, dateYear, dateToday
Dim mgcCmd, var1, var2, var3
Dim WshShell


' ---------------------------------------------------------------------------
' ---------------------------------------------------------------------------
' ---------- CHANGE THE FOLLOWING VALUES BEFORE RUNNING THE SCRIPT ----------
' ---------------------------------------------------------------------------
' ---------------------------------------------------------------------------

' Path to the CountDown images
cdFolder = "cd"

' Background Image to use with the CountDown images
bgImg = "BG.jpg"

' Path to the Composite BG images with CountDown and Background
compDir = "comp"

' ImageMagic: use "magick" for normal installs, path to magick.exe (ex. "C:\ImageMagick\magick.exe") for the portable version
imgMgc = "magick"

' Position of the countdown image, ex: "-gravity center" for centered, "-geometry +15+25" to move from top left corner on the x and y coordinates by pixel value
imgPos = "-gravity center"

' Absolute Path of the folder containing all the images and scripts, changePath.vbs changes this value.
mainDir = " --- RUN changePath.vbs --- "

' ---------------------------------------------------------------------------
' ---------------------------------------------------------------------------
' ---------------------------------------------------------------------------


' Absolute path to the folders and Background image
cdFolder = mainDir & "\" & cdFolder
compDir = mainDir & "\" & compDir
bgImg = mainDir & "\" & bgImg

' Extension of the final Background image, use "jpg" ---------------- "png" "bmp" don't always work (probably due to filesize)
fileExt = "jpg"

Set WshShell = CreateObject("WScript.Shell")
Set fso = CreateObject("Scripting.FileSystemObject")  
Set folder = fso.GetFolder(compDir)  
Set folder2 = fso.GetFolder(cdFolder)

' Converting current date from single digit month and day to two digits 1 -> 01 etc.
dateMonth = Right(String(2, "0") & Month(Date), 2)
dateDay = Right(String(2, "0") & Day(Date), 2)

dateYear = Right(Year(dtNew), 2)
'The current date in YYMMDD format
dateToday = dateMonth & dateDay

' Loop over the CountDown images, to find out if there's an image for the current day
For Each file In folder.Files

	If instr(file, dateToday) > 0 Then

		cdToday = 1

		Exit For
		
	End If
	
Next

' var1 var2 var3 are the three image paths required for ImageMagick		
var2 = """" & bgImg & """"

var3 = """" & compDir & "\" & "WP_" & dateToday & "." & fileExt & """"

' If there's no image for the current day, it gets generated by ImageMagick
If cdToday = 0 Then

	For Each file2 In folder2.Files
		
		If instr(file2, dateToday) > 0 Then
		
			cdToday = file2.Name
			
			var1 = """" & cdFolder & "\" & cdToday & """"

			'ImageMagic command
			mgcCmd = """" & imgMgc & """ composite -compose atop " & imgPos & " " & var1 & " " & var2 & " " & var3
			
			WshShell.Run mgcCmd, 0
			
		End If
	
	Next
	 	
End If

' Delay in ms to give ImageMagick a bit of space/ time to finish
WScript.Sleep 3000

' Running the Powershell Script to change the Wallpaper
runPS = "powershell.exe -noexit -file " & mainDir & "\SetWallpaper.ps1" & " " & Var3 

WshShell.run runPS, 0
